name = "swiftyidwebsite"
description = "This is SwiftyID website project runs on smbCloud."

[project]
id = 21
name = "swiftyidwebsite"
repository = "swiftyidwebsite"
description = "This is SwiftyID website project runs on smbCloud."
created_at = "2025-06-28T14:21:10.885Z"
updated_at = "2025-06-28T14:21:10.885Z"
