name: Swift Build

on:
  push:

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.1.0"
    - name: Get swift version
      run: swift --version
    - name: Build
      run: swift build -v
